// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Change = { change_id: string, commit_id: string, description: string, author: string, timestamp: string, empty: boolean, };
