// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";

export type Diff = { change_id: string, base: string, files: Array<FileDiff>, raw: string, };
