// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Revision = { number: number, commit_id: string, created_at: string, description: string | null, };
