// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { Thread } from "./Thread";

export type Review = { change_id: string, base: string, created_at: string, threads: Array<Thread>, revisions: Array<Revision>, working_commit_id: string | null, };
