// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { ThreadStatus } from "./ThreadStatus";

export type Thread = { id: string, file: string, line_start: number, line_end: number, status: ThreadStatus, comments: Array<Comment>, };
