// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoItem } from "./TodoItem";

export type TodoTree = { root_ids: Array<string>, items: { [key in string]?: TodoItem }, };
