// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoItem = { id: string, text: string, checked: boolean, children: Array<string>, topic_id: string | null, created_at: string, };
