// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopicStatus } from "./TopicStatus";

export type Topic = { id: string, name: string, base: string, changes: Array<string>, status: TopicStatus, created_at: string, };
